### ISSUE TITLE
Something wrong while Installing Dex-Net

### ISSUE THREAD

**Issue by ChuGuoqing** [PickNikRobotics/deep_grasp_demo#20]
First,Thank you for this wonderful repo!

I'm on ROS Noetic, Ubuntu 20.04. While I install Dex-Net following the 'README.md',something wrong happened. Below is my
operation:

1、install anaconda3, create a virtual environment with command ‘conda create -n DexNet-3.7 python = 3.7’, and enter the environment with command 'conda activate DexNet-3.7'. There is no error.

2、python3 -m pip install --upgrade pip. There is no error.

3、wget https://raw.githubusercontent.com/PickNikRobotics/deep_grasp_demo/master/dexnet_install.sh
      wget https://raw.githubusercontent.com/PickNikRobotics/deep_grasp_demo/master/dexnet_requirements.txt
      chmod +x dexnet_install.sh
      ./dexnet_install.sh gpu
      Something wrong happened.
     (1)E: Unable to locate package python-vtk6. I search the website 'https://packages.ubuntu.com/focal/python/',and find that there is no package name python-vtk6 in ubuntu 20.04, so I change  'python-vtk6' to 'python3-vtk*'. It can install successfully, but I don't know whether is it right or not
     (2)While execute the command 'sudo python3 setup.py develop' in folder 'autolab_core' , an error occur: 'error: scipy 1.10.1 is installed but scipy<1.9.2,>=1.8 is required by {'scikit-image'}'.As shown in document 'error2.txt'
     I run the command 'conda list' in the virtual environment, it show 'scipy 1.4.1 pypi_0 pypi', which show there is no package scipy = 1.10.1. As shown in document 'conda_list.txt'
     (3)While execute the command 'sudo python3 setup.py develop' in folder 'gqcnn' , an error occur: 'ERROR: Could not find a version that satisfies the requirement tensorflow-gpu<=1.15.0'.As shown in document 'error3.txt'
     (4)While execute the command 'sudo python3 setup.py develop' in folder 'perception' , an error occur: '[ERROR: Could not find a version that satisfies the requirement tensorflow-gpu<=1.15.0](error: Pillow 7.0.0 is installed but pillow>=8.3.2 is required by {'imageio'})'.As shown in document 'error5.txt'
     (5)While execute the command 'sudo python3 setup.py develop' in folder 'visualization' , an error occur: '[ERROR: Could not find a version that satisfies the requirement tensorflow-gpu<=1.15.0](error: scipy 1.10.1 is installed but scipy<1.9.2,>=1.8 is required by {'scikit-image'})'.As shown in document 'error4.txt'

Does anybody know why the error have happened? Is there anything I can do for the program to run well. I am grateful for any hints or suggestions!

[conda_list.txt](https://github.com/PickNikRobotics/deep_grasp_demo/files/11111577/conda_list.txt)
[error5.txt](https://github.com/PickNikRobotics/deep_grasp_demo/files/11111578/error5.txt)
[error4.txt](https://github.com/PickNikRobotics/deep_grasp_demo/files/11111579/error4.txt)
[error3.txt](https://github.com/PickNikRobotics/deep_grasp_demo/files/11111580/error3.txt)
[error2.txt](https://github.com/PickNikRobotics/deep_grasp_demo/files/11111582/error2.txt)

**Comment by ShivaKPuppala** [comment]
How did you solve ? what are the versions you modified? @ChuGuoqing
